### ISSUE TITLE
FEATURE: Container Image?

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/net.dnsclient#2]
Would you be able to publish a container image for this web app?

I can make one, but I always prefer to have the developer create one so that a new version can be pushed whenever the code is updated.

**Comment by ShreyasZare** [comment]
Thanks for the request. Will try to publish docker image this weekend.

**Comment by ShreyasZare** [comment]
Docker [image](https://hub.docker.com/r/technitium/dns-client) is now published. Do check and let me know your feedback.

**Comment by djarbz** [comment]
Just got around to spinning this up and testing, works great, thanks!
