### ISSUE TITLE
Unknown CA support

### ISSUE THREAD

**Issue by myf5** [TechnitiumSoftware/net.dnsclient#3]
While using it for local environment test, the DoH server's certificate is not signed by trusted CA, it is self sign. 
Is there any workaround to support self-sign cert?
Thanks.

I had copy the self-sign cert to /etc/ssl/certs, but not sure how to specify the cert.

**Comment by myf5** [comment]
here is the error:
`Error! The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch`

**Comment by ShreyasZare** [comment]
Thanks for the post. There is no option currently available to ignore cert validation. Will plan to have some option added later.

The error description says `RemoteCertificateNameMismatch` so its due to the server's domain name that is used not matching the name in the cert. Try using the exact domain name that is included in the cert and see if that works.

**Comment by myf5** [comment]
> Thanks for the post. There is no option currently available to ignore cert validation. Will plan to have some option added later.
> 
> The error description says `RemoteCertificateNameMismatch` so its due to the server's domain name that is used not matching the name in the cert. Try using the exact domain name that is included in the cert and see if that works.

Thanks for prompt reply.
After setting same domain name in the cert, error changed to:
`The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot`
So, should need ignore ssl error fully.

**Comment by ShreyasZare** [comment]
So, right now your only option is to get the cert installed locally to be trusted until an option is available to ignore validation issues.

> I had copy the self-sign cert to /etc/ssl/certs, but not sure how to specify the cert.

Have you run the `update-ca-certificates` command after copying the cert? Also, you may need to restart the DNS client app to make it work.

**Comment by myf5** [comment]
It works after I restart the process. 
The command `update-ca-certificates` will call a hook script, while the script file not included in the image.

**Comment by myf5** [comment]
Thanks.

**Comment by ShreyasZare** [comment]
Thanks for letting me know.
