### ISSUE TITLE
[feature request?] Inject the host's DNS resolvers into the server list?

### ISSUE THREAD

**Issue by junkiebev** [TechnitiumSoftware/net.dnsclient#4]
I'm using this in a container, and interested in querying the container host's authoritative DNS servers - that is to say, the DNS records which would return in the event that the host executed the DNS lookup.

I should think that getting the list would be easy in container-world - it should be simply all lines in `/etc/resolv.conf`, which begin with `nameserver`.

Is it possible to read that into the server's list at runtime? I'm happy to take a crack at it, if it's not antagonistic to this project's aims.

**Comment by ShreyasZare** [comment]
Thanks for the feature suggestion. Adding the locally configured DNS servers in the servers list is possible. I will check this and let you know soon.

**Comment by ShreyasZare** [comment]
I am adding "System DNS" option to the servers list. The DNS Client will automatically pick system's current DNS servers and query them concurrently. I think this should cover the feature you are looking for. Let me know your comments.

**Comment by ShreyasZare** [comment]
Technitium DNS Client v5.3 is now available that adds `system-dns` option to the servers list using which the DNS client can query to DNS servers configured on the system. Do update and let me know your feedback.
