### ISSUE TITLE
[Feature Request] Support basepath different from "/"

### ISSUE THREAD

**Issue by danieldietsch** [TechnitiumSoftware/net.dnsclient#6]
It would be great if I could run the app under a different basepath, perhaps even with an environment variable for docker. 

E.g., instead of http://localhost:8001/, I would like to use http://localhost:8001/dnsclient.

Then I could run it behind a reverse proxy.

**Comment by ShreyasZare** [comment]
Thanks for the request. You can still run it with a reverse proxy by using a separate subdomain name for it. In fact the dnsclient.net website is running on nginx that does reverse proxy to the dnsclient app.

Does that work for you?

**Comment by danieldietsch** [comment]
Yes, of course. It would just be neat to not need a separate subdomain.

**Comment by ShreyasZare** [comment]
Ok will get that changed in next update.

**Comment by ShreyasZare** [comment]
DNS Client v7.1 is now available that uses relative paths. Do update and let me know your feedback.
